apiVersion: v1
kind: Service
metadata:
  name: {{ include "svc.name" . }}
  labels: {{- include "svc.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector: {{- include "svc.selector" . | nindent 4 }}
  ports:
    {{- if gt (int .Values.ports.grpc) 0 }}
    - name: grpc
      port: {{ .Values.ports.grpc }}
      targetPort: grpc
      appProtocol: h2c
    {{- end }}
    {{- if gt (int .Values.ports.http) 0 }}
    - name: http
      port: {{ .Values.ports.http }}
      targetPort: http
      appProtocol: http
    {{- end }}
    {{- if gt (int .Values.ports.metrics) 0 }}
    - name: metrics
      port: {{ .Values.ports.metrics }}
      targetPort: metrics
    {{- end }}
