serviceName: inventory-service
image: { repository: ghcr.io/eusahn/inventory-service
ports: { http: 0, grpc: 50051, metrics: 9090 }
env:
  SERVICE_NAME: inventory-service
  GRPC_PORT: "50051"
  METRICS_PORT: "9090"
  KAFKA_BROKERS: "kafka-kafka-bootstrap.kafka.svc.cluster.local:9092"
  KAFKA_GROUP_ID: "inventory-service"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.observability.svc.cluster.local:4318"
envFrom:
  - secretRef: { name: inventory-db }
