apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources-shopcart
  labels:
    grafana_datasource: "1"
data:
  shopcart-datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        access: proxy
        url: http://loki.observability.svc.cluster.local:3100
        jsonData:
          derivedFields:
            - datasourceUid: tempo
              matcherRegex: "trace_id=([a-f0-9]+)"
              name: TraceID
              url: "$${__value.raw}"
      - name: Tempo
        type: tempo
        uid: tempo
        access: proxy
        url: http://tempo.observability.svc.cluster.local:3100
        jsonData:
          tracesToLogsV2:
            datasourceUid: loki
            spanStartTimeShift: "-1h"
            spanEndTimeShift: "1h"
            tags: ['service.name']
            filterByTraceID: true
          serviceMap:
            datasourceUid: prometheus
      - name: Prometheus
        type: prometheus
        uid: prometheus
        access: proxy
        url: http://kps-prometheus.observability.svc.cluster.local:9090
        isDefault: true
